<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create admin user
        User::create([
            'first_name' => 'Admin',
            'last_name' => 'User',
            'email' => 'admin@dentalcourse.com',
            'phone' => '+1-555-0001',
            'date_of_birth' => '1980-01-15',
            'gender' => 'male',
            'address' => '123 Admin Street',
            'city' => 'New York',
            'state' => 'NY',
            'zip_code' => '10001',
            'country' => 'United States',
            'emergency_name' => 'Jane Admin',
            'emergency_relationship' => 'Spouse',
            'emergency_phone' => '+1-555-0002',
            'role' => 'admin',
            'status' => 'active',
            'password' => Hash::make('admin123'),
            'email_verified_at' => now(),
        ]);

        // Create sample students
        $students = [
            [
                'first_name' => 'John',
                'last_name' => 'Smith',
                'email' => 'john.smith@email.com',
                'phone' => '+1-555-0101',
                'date_of_birth' => '1990-03-15',
                'gender' => 'male',
                'address' => '456 Oak Avenue',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'zip_code' => '90210',
                'country' => 'United States',
                'emergency_name' => 'Mary Smith',
                'emergency_relationship' => 'Wife',
                'emergency_phone' => '+1-555-0102',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Emily',
                'last_name' => 'Johnson',
                'email' => 'emily.johnson@email.com',
                'phone' => '+1-555-0201',
                'date_of_birth' => '1988-07-22',
                'gender' => 'female',
                'address' => '789 Pine Street',
                'city' => 'Chicago',
                'state' => 'IL',
                'zip_code' => '60601',
                'country' => 'United States',
                'emergency_name' => 'Robert Johnson',
                'emergency_relationship' => 'Husband',
                'emergency_phone' => '+1-555-0202',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'email' => 'michael.brown@email.com',
                'phone' => '+1-555-0301',
                'date_of_birth' => '1992-11-08',
                'gender' => 'male',
                'address' => '321 Elm Drive',
                'city' => 'Houston',
                'state' => 'TX',
                'zip_code' => '77001',
                'country' => 'United States',
                'emergency_name' => 'Lisa Brown',
                'emergency_relationship' => 'Sister',
                'emergency_phone' => '+1-555-0302',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'Davis',
                'email' => 'sarah.davis@email.com',
                'phone' => '+1-555-0401',
                'date_of_birth' => '1985-04-12',
                'gender' => 'female',
                'address' => '654 Maple Lane',
                'city' => 'Phoenix',
                'state' => 'AZ',
                'zip_code' => '85001',
                'country' => 'United States',
                'emergency_name' => 'David Davis',
                'emergency_relationship' => 'Father',
                'emergency_phone' => '+1-555-0402',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Wilson',
                'email' => 'james.wilson@email.com',
                'phone' => '+1-555-0501',
                'date_of_birth' => '1991-09-25',
                'gender' => 'male',
                'address' => '987 Cedar Court',
                'city' => 'Philadelphia',
                'state' => 'PA',
                'zip_code' => '19101',
                'country' => 'United States',
                'emergency_name' => 'Jennifer Wilson',
                'emergency_relationship' => 'Mother',
                'emergency_phone' => '+1-555-0502',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Jessica',
                'last_name' => 'Miller',
                'email' => 'jessica.miller@email.com',
                'phone' => '+1-555-0601',
                'date_of_birth' => '1987-12-03',
                'gender' => 'female',
                'address' => '147 Birch Boulevard',
                'city' => 'San Antonio',
                'state' => 'TX',
                'zip_code' => '78201',
                'country' => 'United States',
                'emergency_name' => 'Mark Miller',
                'emergency_relationship' => 'Brother',
                'emergency_phone' => '+1-555-0602',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Daniel',
                'last_name' => 'Garcia',
                'email' => 'daniel.garcia@email.com',
                'phone' => '+1-555-0701',
                'date_of_birth' => '1989-06-18',
                'gender' => 'male',
                'address' => '258 Willow Way',
                'city' => 'San Diego',
                'state' => 'CA',
                'zip_code' => '92101',
                'country' => 'United States',
                'emergency_name' => 'Maria Garcia',
                'emergency_relationship' => 'Wife',
                'emergency_phone' => '+1-555-0702',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Ashley',
                'last_name' => 'Martinez',
                'email' => 'ashley.martinez@email.com',
                'phone' => '+1-555-0801',
                'date_of_birth' => '1993-02-14',
                'gender' => 'female',
                'address' => '369 Spruce Street',
                'city' => 'Dallas',
                'state' => 'TX',
                'zip_code' => '75201',
                'country' => 'United States',
                'emergency_name' => 'Carlos Martinez',
                'emergency_relationship' => 'Father',
                'emergency_phone' => '+1-555-0802',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Christopher',
                'last_name' => 'Anderson',
                'email' => 'christopher.anderson@email.com',
                'phone' => '+1-555-0901',
                'date_of_birth' => '1986-10-30',
                'gender' => 'male',
                'address' => '741 Poplar Place',
                'city' => 'San Jose',
                'state' => 'CA',
                'zip_code' => '95101',
                'country' => 'United States',
                'emergency_name' => 'Michelle Anderson',
                'emergency_relationship' => 'Sister',
                'emergency_phone' => '+1-555-0902',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Amanda',
                'last_name' => 'Taylor',
                'email' => 'amanda.taylor@email.com',
                'phone' => '+1-555-1001',
                'date_of_birth' => '1994-05-07',
                'gender' => 'female',
                'address' => '852 Hickory Hill',
                'city' => 'Austin',
                'state' => 'TX',
                'zip_code' => '73301',
                'country' => 'United States',
                'emergency_name' => 'Thomas Taylor',
                'emergency_relationship' => 'Husband',
                'emergency_phone' => '+1-555-1002',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
        ];

        foreach ($students as $student) {
            $student['role'] = 'student';
            $student['status'] = 'active';
            $student['password'] = Hash::make('password123');
            $student['email_verified_at'] = now();
            
            User::create($student);
        }

        // Create additional random users using factory if available
        // User::factory(20)->create();
    }
}
