<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create admin user
        User::create([
            'first_name' => 'Admin',
            'last_name' => 'User',
            'email' => 'admin@dentalcourse.com',
            'phone' => '+1-555-0001',
            'date_of_birth' => '1980-01-15',
            'gender' => 'male',
            'nationality' => 'Omani',
            'whatsapp_available' => true,
            'clinical_experience' => '10+',
            'oman_license' => 'yes',
            'dental_degree' => 'DDS',
            'graduation_institute' => 'Sultan Qaboos University',
            'graduation_year' => 2005,
            'current_workplace' => 'Muscat Dental Center',
            'implantology_experience' => 'advanced',
            'how_heard_about_course' => 'Professional network',
            'enrollment_reason' => 'To enhance my knowledge and skills in dental implantology.',
            'role' => 'admin',
            'status' => 'active',
            'password' => Hash::make('admin123'),
            'email_verified_at' => now(),
        ]);

        // Create sample students
        $students = [
            [
                'first_name' => 'John',
                'last_name' => 'Smith',
                'email' => 'john.smith@email.com',
                'phone' => '+1-555-0101',
                'date_of_birth' => '1990-03-15',
                'gender' => 'male',
                'nationality' => 'American',
                'whatsapp_available' => true,
                'clinical_experience' => '5-9',
                'oman_license' => 'no',
                'dental_degree' => 'BDS',
                'graduation_institute' => 'Harvard School of Dental Medicine',
                'graduation_year' => 2015,
                'current_workplace' => 'Smith Dental Clinic',
                'implantology_experience' => 'basic',
                'how_heard_about_course' => 'Online search',
                'enrollment_reason' => 'To learn advanced implantology techniques.',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Emily',
                'last_name' => 'Johnson',
                'email' => 'emily.johnson@email.com',
                'phone' => '+1-555-0201',
                'date_of_birth' => '1988-07-22',
                'gender' => 'female',
                'nationality' => 'British',
                'whatsapp_available' => false,
                'clinical_experience' => '10+',
                'oman_license' => 'yes',
                'dental_degree' => 'Masters in Oral Surgery',
                'graduation_institute' => 'King\'s College London',
                'graduation_year' => 2012,
                'current_workplace' => 'London Dental Hospital',
                'implantology_experience' => 'intermediate',
                'how_heard_about_course' => 'Colleague recommendation',
                'enrollment_reason' => 'To update my skills with latest implantology methods.',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'email' => 'michael.brown@email.com',
                'phone' => '+1-555-0301',
                'date_of_birth' => '1992-11-08',
                'gender' => 'male',
                'nationality' => 'Canadian',
                'whatsapp_available' => true,
                'clinical_experience' => '1-4',
                'oman_license' => 'no',
                'dental_degree' => 'BDS',
                'graduation_institute' => 'University of Toronto',
                'graduation_year' => 2018,
                'current_workplace' => 'Toronto Dental Group',
                'implantology_experience' => 'very_little_to_none',
                'how_heard_about_course' => 'Social media',
                'enrollment_reason' => 'Starting my career in implantology.',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'Davis',
                'email' => 'sarah.davis@email.com',
                'phone' => '+1-555-0401',
                'date_of_birth' => '1985-04-12',
                'gender' => 'female',
                'nationality' => 'Australian',
                'whatsapp_available' => true,
                'clinical_experience' => '10+',
                'oman_license' => 'no',
                'dental_degree' => 'PhD in Dentistry',
                'graduation_institute' => 'University of Sydney',
                'graduation_year' => 2010,
                'current_workplace' => 'Sydney Dental Institute',
                'implantology_experience' => 'advanced',
                'how_heard_about_course' => 'Conference',
                'enrollment_reason' => 'To learn latest techniques and network with professionals.',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Wilson',
                'email' => 'james.wilson@email.com',
                'phone' => '+1-555-0501',
                'date_of_birth' => '1991-09-25',
                'gender' => 'male',
                'nationality' => 'Indian',
                'whatsapp_available' => true,
                'clinical_experience' => '5-9',
                'oman_license' => 'yes',
                'dental_degree' => 'BDS',
                'graduation_institute' => 'All India Institute of Medical Sciences',
                'graduation_year' => 2016,
                'current_workplace' => 'Muscat Dental Clinic',
                'implantology_experience' => 'basic',
                'how_heard_about_course' => 'Website',
                'enrollment_reason' => 'To expand my practice in Oman.',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Jessica',
                'last_name' => 'Miller',
                'email' => 'jessica.miller@email.com',
                'phone' => '+1-555-0601',
                'date_of_birth' => '1987-12-03',
                'gender' => 'female',
                'nationality' => 'German',
                'whatsapp_available' => false,
                'clinical_experience' => '5-9',
                'oman_license' => 'no',
                'dental_degree' => 'Masters in Oral Surgery',
                'graduation_institute' => 'Charité - Universitätsmedizin Berlin',
                'graduation_year' => 2013,
                'current_workplace' => 'Berlin Dental Center',
                'implantology_experience' => 'intermediate',
                'how_heard_about_course' => 'Professional journal',
                'enrollment_reason' => 'To enhance my surgical skills in implantology.',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Daniel',
                'last_name' => 'Garcia',
                'email' => 'daniel.garcia@email.com',
                'phone' => '+1-555-0701',
                'date_of_birth' => '1989-06-18',
                'gender' => 'male',
                'nationality' => 'Spanish',
                'whatsapp_available' => true,
                'clinical_experience' => '5-9',
                'oman_license' => 'no',
                'dental_degree' => 'BDS',
                'graduation_institute' => 'Universidad Complutense Madrid',
                'graduation_year' => 2012,
                'current_workplace' => 'Garcia Dental Clinic',
                'implantology_experience' => 'basic',
                'how_heard_about_course' => 'Social media',
                'enrollment_reason' => 'To learn advanced implantology techniques.',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Ashley',
                'last_name' => 'Martinez',
                'email' => 'ashley.martinez@email.com',
                'phone' => '+1-555-0801',
                'date_of_birth' => '1993-02-14',
                'gender' => 'female',
                'nationality' => 'Mexican',
                'whatsapp_available' => true,
                'clinical_experience' => '1-4',
                'oman_license' => 'no',
                'dental_degree' => 'DDS',
                'graduation_institute' => 'Universidad Nacional Autónoma de México',
                'graduation_year' => 2016,
                'current_workplace' => 'Martinez Family Dentistry',
                'implantology_experience' => 'very_little_to_none',
                'how_heard_about_course' => 'Colleague recommendation',
                'enrollment_reason' => 'To start my journey in implantology.',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Christopher',
                'last_name' => 'Anderson',
                'email' => 'christopher.anderson@email.com',
                'phone' => '+1-555-0901',
                'date_of_birth' => '1986-10-30',
                'gender' => 'male',
                'nationality' => 'American',
                'whatsapp_available' => false,
                'clinical_experience' => '10+',
                'oman_license' => 'yes',
                'dental_degree' => 'DDS, MS',
                'graduation_institute' => 'University of Michigan School of Dentistry',
                'graduation_year' => 2009,
                'current_workplace' => 'Anderson Oral Surgery',
                'implantology_experience' => 'intermediate',
                'how_heard_about_course' => 'Professional conference',
                'enrollment_reason' => 'To refine my implantology skills.',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Amanda',
                'last_name' => 'Taylor',
                'email' => 'amanda.taylor@email.com',
                'phone' => '+1-555-1001',
                'date_of_birth' => '1994-05-17',
                'gender' => 'female',
                'nationality' => 'Australian',
                'whatsapp_available' => true,
                'clinical_experience' => '1-4',
                'oman_license' => 'no',
                'dental_degree' => 'BDS',
                'graduation_institute' => 'University of Sydney',
                'graduation_year' => 2017,
                'current_workplace' => 'Taylor Dental Practice',
                'implantology_experience' => 'very_little_to_none',
                'how_heard_about_course' => 'Online search',
                'enrollment_reason' => 'To expand my dental practice services.',
                'role' => 'student',
                'status' => 'active',
                'password' => Hash::make('student123'),
                'email_verified_at' => now(),
            ],
        ];

        foreach ($students as $student) {
            User::create($student);
        }

        // Create sample instructors
        $instructors = [
            [
                'first_name' => 'Dr. Robert',
                'last_name' => 'Thompson',
                'email' => 'robert.thompson@dentalcourse.com',
                'phone' => '+1-555-2001',
                'date_of_birth' => '1975-08-20',
                'gender' => 'male',
                'nationality' => 'American',
                'whatsapp_available' => true,
                'clinical_experience' => '10+',
                'oman_license' => 'yes',
                'dental_degree' => 'DDS',
                'graduation_institute' => 'Harvard School of Dental Medicine',
                'graduation_year' => 2000,
                'current_workplace' => 'Thompson Dental Clinic',
                'implantology_experience' => 'advanced',
                'how_heard_about_course' => 'Professional network',
                'enrollment_reason' => 'To enhance teaching skills in implantology',
                'role' => 'instructor',
                'status' => 'active',
                'password' => Hash::make('instructor123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Dr. Lisa',
                'last_name' => 'White',
                'email' => 'lisa.white@dentalcourse.com',
                'phone' => '+1-555-2002',
                'date_of_birth' => '1978-12-05',
                'gender' => 'female',
                'nationality' => 'Canadian',
                'whatsapp_available' => false,
                'clinical_experience' => '10+',
                'oman_license' => 'yes',
                'dental_degree' => 'DMD',
                'graduation_institute' => 'University of Toronto Faculty of Dentistry',
                'graduation_year' => 2003,
                'current_workplace' => 'White Dental Associates',
                'implantology_experience' => 'advanced',
                'how_heard_about_course' => 'Dental conference',
                'enrollment_reason' => 'To stay updated with latest implantology techniques',
                'role' => 'instructor',
                'status' => 'active',
                'password' => Hash::make('instructor123'),
                'email_verified_at' => now(),
            ],
            [
                'first_name' => 'Dr. Mark',
                'last_name' => 'Harris',
                'email' => 'mark.harris@dentalcourse.com',
                'phone' => '+1-555-2003',
                'date_of_birth' => '1972-03-28',
                'gender' => 'male',
                'nationality' => 'British',
                'whatsapp_available' => true,
                'clinical_experience' => '10+',
                'oman_license' => 'yes',
                'dental_degree' => 'BDS, MSc',
                'graduation_institute' => 'King\'s College London Dental Institute',
                'graduation_year' => 1995,
                'current_workplace' => 'Harris Oral Surgery Center',
                'implantology_experience' => 'advanced',
                'how_heard_about_course' => 'Medical journal',
                'enrollment_reason' => 'To contribute expertise in advanced implantology',
                'role' => 'instructor',
                'status' => 'active',
                'password' => Hash::make('instructor123'),
                'email_verified_at' => now(),
            ],
        ];

        foreach ($instructors as $instructor) {
            User::create($instructor);
        }
    }
}
